/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lin_ccalljava_Jni */

#ifndef _Included_com_lin_ccalljava_Jni
#define _Included_com_lin_ccalljava_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lin_ccalljava_Jni
 * Method:    addCCallJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lin_ccalljava_Jni_addCCallJava
  (JNIEnv *, jobject);

/*
 * Class:     com_lin_ccalljava_Jni
 * Method:    sayHelloCCallJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lin_ccalljava_Jni_sayHelloCCallJava
  (JNIEnv *, jobject);

/*
 * Class:     com_lin_ccalljava_Jni
 * Method:    printStringCCallJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lin_ccalljava_Jni_printStringCCallJava
  (JNIEnv *, jobject);

/*
 * Class:     com_lin_ccalljava_Jni
 * Method:    staticCCallJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lin_ccalljava_Jni_staticCCallJava
  (JNIEnv *, jobject);



#ifdef __cplusplus
}
#endif
#endif
