/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lin_jni63_Jni */

#ifndef _Included_com_lin_jni63_Jni
#define _Included_com_lin_jni63_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lin_jni63_Jni
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lin_jni63_Jni_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lin_jni63_Jni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lin_jni63_Jni_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lin_jni63_Jni
 * Method:    append
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_lin_jni63_Jni_append
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_lin_jni63_Jni
 * Method:    check
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lin_jni63_Jni_check
  (JNIEnv *, jobject, jstring);


#ifdef __cplusplus
}
#endif
#endif
